version: 2.1

jobs:
  build_auth:
    docker:
      - image: circleci/golang:1.16
    # working_directory: /go/src/github.com/vksssd/intercom
    steps:
      - checkout

      # Build and test auth-service
      - setup_remote_docker
      - run:
          name: Build and test auth-service
          command: |
            cd auth-service
            circleci config process .circleci/config.yml > processed_config.yml
            circleci local execute -c processed_config.yml
workflows:
  version: 2
  build:
    jobs:
      - build_auth